config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions', 
    registrations: 'members/registrations'
  }

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  
  # Constants
  QTT_PER_PAGE = 6

  # RatyRAte gem
  ratyrate_rateable 'quality'

  # Callbacks
  before_save :md_to_html

  #Associations
  belongs_to :member
  belongs_to :category, counter_cache: true
  has_many :comments

  #Validates
  validates :title, 
  :description_short, 
  :description_md,  
  :category, 
  :picture, 
  :finish_date, 
  presence: true
  validates :price, numericality: { greater_than: 0 }

  # Scopes
  scope :descending_order, ->(page) { order(created_at: :desc).page(page).per(QTT_PER_PAGE) }
  scope :search, ->(term, page) { where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(QTT_PER_PAGE) }
  scope :to_the, ->(member, page) { where(member: member) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(QTT_PER_PAGE) }
  
  scope :random, ->(quantity) {
    if Rails.env.production?
      limit(quantity).order("RAND()") # MySQL
    else
      limit(quantity).order("RANDOM()") # SQLite
     end
   }

  # paperclip
  has_attached_file :picture, styles: { large: "900x350#", medium: "700x400#", thumb: "100x100>" }, 
  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # gem money-rails
  monetize :price_cents

  def second
    self[1]
  end

  def third
    self[2]
  end

  private

  def md_to_html
    options = {
      filter_html: true,
      link_attributes: {
        rel: "nofollow",
        target: "_blank"
      }
    }
    extensions = {
      space_after_headers: true,
      autolink: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    self.description = markdown.render(self.description_md)
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	#Constants
	ROLES = {:full_access => 0, :restricted_access => 1}
	#Enums
	enum role: ROLES

	# Scopes
	scope :with_full_access, -> { where(role: ROLES[:full_access]) }
	scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

	# def self.with_full_access
	#   where(role: 'full_access')
	# end

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base

	# Gem Friendly Id
	include FriendlyId
	friendly_id :description, use: :slugged

	# Associotions
	has_many :ads

	# Validations
	validates_presence_of :description

	# Scopes
	scope :order_by_description, -> { order(:description) }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ActiveRecord::Base

	# RateRaty gem
	ratyrate_rater
	
	# Associations
	has_many :ads
	has_one :profile_member
	accepts_nested_attributes_for :profile_member

	#Validations
	validate :nested_attributes

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :validatable

	private

	def nested_attributes
		if nested_attributes_blank?
			errors.add( :base, I18n.t('messages.error_nested_attributes') )
		end
	end

	def nested_attributes_blank?
		profile_member.first_name.blank? || profile_member.second_name.blank?
	end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_member.rb
class ProfileMember < ActiveRecord::Base

	belongs_to :member

	def full_name
		"#{self.first_name} #{self.second_name}"
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :store_current_location, :unless => :devise_controller?

  # Pundit
  include Pundit

  # Manages Pundit errors
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Set Layout
  layout :layout_by_resource

  private

  def store_current_location
    store_location_for(:member, request.url)
  end

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
  	else
  		"application"
  	end
  end

  def user_not_authorized
  	flash[:alert] = I18n.t('messages.not_authorized')
  	redirect_to(request.referrer || root_path)
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout "backoffice"

	def pundit_user
		current_admin # current_user to Pundit
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	layout "site"
end

app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		current_member
	end

	def devise_sign_in?
		params[:controller] == 'members/sessions' ? '' : 'display:none;'
	end

	def devise_sign_up?
		params[:controller] == 'members/registrations' ? '' : 'display:none;'
	end
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<!-- Page Content -->
<h1 class="page-header"><%= @admin.model_name.human(count: 2) %></h1>

<% if @admin.errors.any? %>
<div class="alert alert-danger alert-dismissable">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<ul>
		<% @admin.errors.full_messages.each do |messages| %>
		<li><%= messages %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="panel panel-default">
	<div class="panel-heading">
		<%= action %>
	</div>
	<!-- /.panel-heading -->
	<div class="panel-body">
		<div class="col-lg-6">
			<%= form_for([:backoffice, @admin]) do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class:"form-control", placeholder:"#{t('placeholder.name')}" %>
			</div>
			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, class:"form-control", placeholder:"#{t('placeholder.email')}" %>
			</div>
			<% if policy(@admin).edit? %>
			<div class="form-group">
				<%= f.label :role %>
				<%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
				<div class="radio">
					<%= b.label { b.radio_button + b.text } %>
				</div>
				<% end %>
			</div>
			<% end %>
			<div class="form-group">
				<%= f.label :password %>
				<%= f.text_field :password, type:"password", class:"form-control", placeholder:"#{t('placeholder.password')}" %>
			</div>
			<div class="form-group">
				<%= f.label :password_confirmation %>
				<%= f.text_field :password_confirmation, type:"password", class:"form-control", placeholder:"#{t('placeholder.password_confirm')}" %>
			</div>
			<button type="submit" class="btn btn-default"><%= t('buttons.save') %></button>
			<% end %>
		</div>
	</div>
	<!-- /.panel-body -->
</div>

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="sendMaiModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="sendMaiModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <div class="modal-body">
        <%=form_tag backoffice_send_mail_index_path, remote: true do %>
          <div class="form-group">
            <label for="recipient-email" class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field :send_email, :recipient_email, class: 'form-control', id: 'recipient-email', readonly: true %>
          </div>
          <div class="form-group">
            <label for="subject-text" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field :send_email, :subject_text, class: 'form-control', id: 'subject-text', required: true %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %>:</label>
            <%= text_area :send_email, :message_text, class: 'form-control', id: 'message-text', 
            required: true %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag t('buttons.send_message'), class: "btn btn-primary", id: 'send_message' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
	<%= javascript_tag "$.notify({ message: '#{notice}' }, 
	{ type: 'success', placement: { from: 'top', align: 'center' }});" %>
<% end %>

<% if alert %>
	<script>
		<%= javascript_tag "$.notify({ message: '#{alert}' }, 
		{ type: 'danger', placement: { from: 'top', align: 'center' }});" %>
	</script>
<% end %>